# AUTO-GENERATED by NOS - Do not edit manually
# Source: examples\minimal.node:2:0

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile,
from rcl_interfaces.msg import ParameterDescriptor,
from nos.runtime import NOSNode,

class SimpleNodeBase(NOSNode):
    """Auto-generated base class for SimpleNode node."""

    def __init__(self, node_name: str = 'simple_node'):
        super().__init__(node_name)

        # Parameter declarations
        self._declare_nos_parameters()

        # Setup communications
        self._setup_communications()

        # Call user initialization
        self.on_init()

    def _declare_nos_parameters(self):
        self.declare_parameter('p', 1)

    def _setup_communications(self):
        pass






def main(args=None):
    rclpy.init(args=args)
    node = SimpleNodeBase()
    executor = rclpy.executors.SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()

