# AUTO-GENERATED by NOS - Do not edit manually
# Source: examples\lidar_processor.node:8:0

import rclpy
from rclpy.node import Node
from rclpy.qos import QoSProfile,
from rcl_interfaces.msg import ParameterDescriptor,
from nos.runtime import NOSNode,
from diagnostic_msgs.msg import *
from sensor_msgs.msg import *

class LidarProcessorBase(NOSLifecycleNode):
    """Auto-generated base class for LidarProcessor node."""

    def __init__(self, node_name: str = 'lidar_processor'):
        super().__init__(node_name)

        # Parameter declarations
        self._declare_nos_parameters()

        # Setup communications
        self._setup_communications()

        # Call user initialization
        self.on_init()

    @property
    def frame_id(self):
        return self.get_parameter('frame_id').value

    @property
    def scan_topic(self):
        return self.get_parameter('scan_topic').value

    @property
    def publish_rate(self):
        return self.get_parameter('publish_rate').value

    @property
    def min_range(self):
        return self.get_parameter('min_range').value

    @property
    def max_range(self):
        return self.get_parameter('max_range').value

    @property
    def filter_config_enabled(self):
        return self.get_parameter('filter_config.enabled').value

    @property
    def filter_config_window_size(self):
        return self.get_parameter('filter_config.window_size').value

    @property
    def filter_config_algorithm(self):
        return self.get_parameter('filter_config.algorithm').value

    @property
    def filter_config(self):
        return self.get_parameter('filter_config').value


    def _declare_nos_parameters(self):
        self.declare_parameter('frame_id', "laser_frame")
        self.declare_parameter('scan_topic', "/scan")
        self.declare_parameter('publish_rate', 10.0)
        self.declare_parameter('min_range', 0.1)
        self.declare_parameter('max_range', 30.0)
        self.declare_parameter('filter_config.enabled', None)
        self.declare_parameter('filter_config.window_size', None)
        self.declare_parameter('filter_config.algorithm', None)

    def _setup_communications(self):
        self._scan_sub = self.create_subscription(
            LaserScan, scan_topic, self._on_scan_received, 10
        )
        self._imu_sub = self.create_subscription(
            Imu, "/imu/data", self._on_imu_received, 10
        )

        self.processed_scan = self.create_publisher(
            LaserScan, "/scan/processed", 10
        )
        self.diagnostics = self.create_publisher(
            DiagnosticArray, "/diagnostics", 10
        )

        self._set_parameters_srv = self.create_service(
            SetBool, "~/set_enabled", self._set_parameters_callback
        )

    def _on_scan_received(self, msg: LaserScan):
        """Wrapper for scan subscription callback."""
        try:
            self.on_scan_received(msg)
        except Exception as e:
            self.get_logger().error(f"Error in scan callback: {e}")

    def on_scan_received(self, msg: LaserScan):
        """Override in subclass to handle scan messages."""
        pass

    def _on_imu_received(self, msg: Imu):
        """Wrapper for imu subscription callback."""
        try:
            self.on_imu_received(msg)
        except Exception as e:
            self.get_logger().error(f"Error in imu callback: {e}")

    def on_imu_received(self, msg: Imu):
        """Override in subclass to handle imu messages."""
        pass

    def _set_parameters_callback(self, request, response):
        """Wrapper for set_parameters service callback."""
        try:
            return self.on_set_parameters_request(request, response)
        except Exception as e:
            self.get_logger().error(f"Error in set_parameters service: {e}")
            response.success = False
            return response

    def on_set_parameters_request(self, request, response):
        """Override in subclass to handle set_parameters requests."""
        response.success = True
        return response

    def on_init(self):
        """User initialization callback."""
        try:
        self.filter.initialize()
        self.get_logger().info("LidarProcessor initialized")
        except Exception as e:
            self.get_logger().error(f"Error in on_init callback: {e}")
            raise  # Re-raise to allow upstream handling

    def on_shutdown(self):
        """User shutdown callback."""
        try:
        self.filter.cleanup()
        self.get_logger().info("LidarProcessor shutting down")
        except Exception as e:
            self.get_logger().error(f"Error in on_shutdown callback: {e}")
            raise  # Re-raise to allow upstream handling

    def scan_received(self, msg: LaserScan):
        """User callback: scan_received."""
        try:
        # Filter and transform the scan data
        if self.filter_config_enabled:
            filtered = self.filter.process(msg)
        else:
            filtered = msg

        # Transform to target frame
        transformed = self.transformer.transform(filtered, self.frame_id)

        # Publish processed scan
        self.processed_scan.publish(transformed)

        # Update diagnostics
        self.update_diagnostics("scan_processed", True)
        except Exception as e:
            self.get_logger().error(f"Error in scan_received callback: {e}")
            raise  # Re-raise to allow upstream handling

    def imu_received(self, msg: Imu):
        """User callback: imu_received."""
        try:
        # Store IMU data for sensor fusion
        self.latest_imu = msg
        except Exception as e:
            self.get_logger().error(f"Error in imu_received callback: {e}")
            raise  # Re-raise to allow upstream handling

    def set_parameters_request(self, req: Request, res: Response):
        """User callback: set_parameters_request."""
        try:
        res.success = True
        res.message = "Parameters updated"
        return res
        except Exception as e:
            self.get_logger().error(f"Error in set_parameters_request callback: {e}")
            raise  # Re-raise to allow upstream handling

    def on_parameter_change(self, enabled: bool):
        """User callback: on_parameter_change."""
        try:
        if enabled:
            self.get_logger().info("Filter enabled")
            self.filter.enable()
        else:
            self.get_logger().info("Filter disabled")
            self.filter.disable()
        except Exception as e:
            self.get_logger().error(f"Error in on_parameter_change callback: {e}")
            raise  # Re-raise to allow upstream handling


    def on_configure(self, state):
        """Configure the node."""
        self._setup_communications()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state):
        """Activate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_deactivate(self, state):
        """Deactivate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_cleanup(self, state):
        """Cleanup the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown(self, state):
        """Shutdown the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS



def main(args=None):
    rclpy.init(args=args)
    node = LidarProcessorBase()
    executor = rclpy.executors.SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()

