"""Launch file transpiler for NOS.

Converts NOS launch declarations to ROS2 Python launch files
with full support for groups, containers, and event handling.
"""

from typing import Dict, Any, List, Optional
from .generator import CodeGenerator, GenerationOutput
from ..ast import nodes
from ..semantic import SymbolTable


class LaunchTranspiler(CodeGenerator):
    """Transpiles NOS launch declarations to ROS2 Python launch files.

    Generates standard ROS2 launch files that are fully compatible
    with the ROS2 launch system.
    """

    def __init__(self, options: Dict[str, Any] = None):
        super().__init__(options)
        self.launch_counter = 0

    def generate(self, ast: nodes.ASTNode, symbol_table: SymbolTable) -> GenerationOutput:
        """Generate launch files from AST."""
        self.output = GenerationOutput()

        if isinstance(ast, nodes.File):
            for decl in ast.declarations:
                if isinstance(decl, nodes.LaunchDecl):
                    self._transpile_launch(decl)
        elif isinstance(ast, nodes.LaunchDecl):
            self._transpile_launch(ast)

        return self.output

    def _transpile_launch(self, launch: nodes.LaunchDecl) -> None:
        """Transpile a single launch declaration."""
        self.launch_counter += 1

        # Generate imports
        imports = self._generate_launch_imports(launch)

        # Generate launch description function
        launch_func = self._generate_launch_function(launch)

        # Combine into output file
        content = f'''# AUTO-GENERATED by NOS Launch Transpiler
# Source: {launch.location}
# Launch: {launch.name}

{imports}

{launch_func}
'''

        file_name = f"{self._camel_to_snake(launch.name)}_launch.py"
        self.output.add_file(file_name, content)

    def _generate_launch_imports(self, launch: nodes.LaunchDecl) -> str:
        """Generate import statements for launch file."""
        imports = [
            "from launch import LaunchDescription",
            "from launch.actions import DeclareLaunchArgument, GroupAction, IncludeLaunchDescription",
            "from launch.conditions import IfCondition, UnlessCondition",
            "from launch.substitutions import LaunchConfiguration, TextSubstitution",
            "from launch.launch_description_sources import PythonLaunchDescriptionSource",
            "from launch_ros.actions import Node, ComposableNodeContainer",
            "from launch_ros.descriptions import ComposableNode",
            "from launch_ros.substitutions import FindPackageShare",
        ]

        # Add conditional imports for events/lifecycle
        if launch.events:
            imports.append("from launch.event_handlers import OnProcessStart")

        if launch.lifecycle_manager:
            imports.append("from launch_ros.actions import LifecycleNode")
            imports.append("from launch_ros.event_handlers import OnStateTransition")

        return "\n".join(imports)

    def _generate_launch_function(self, launch: nodes.LaunchDecl) -> str:
        """Generate the generate_launch_description function."""
        lines = ["def generate_launch_description():"]

        # Generate LaunchConfiguration variables
        config_vars = self._generate_config_variables(launch)
        if config_vars:
            lines.extend(config_vars)
            lines.append("")

        # Generate DeclareLaunchArgument actions
        declare_args = self._generate_argument_declarations(launch)
        if declare_args:
            lines.extend(declare_args)
            lines.append("")

        # Generate launch actions list
        lines.append("    # Launch actions")
        lines.append("    actions = []")
        lines.append("")

        # Process groups
        for group in launch.groups:
            group_code = self._generate_group_action(group)
            lines.append(f"    {group_code}")
            lines.append("    actions.append(group_action)")
            lines.append("")

        # Process containers
        for container in launch.containers:
            container_code = self._generate_container_action(container)
            lines.append(f"    {container_code}")
            lines.append("    actions.append(container_action)")
            lines.append("")

        # Process includes
        for include in launch.includes:
            include_code = self._generate_include_action(include)
            lines.append(f"    {include_code}")
            lines.append("    actions.append(include_action)")
            lines.append("")

        # Process lifecycle manager
        if launch.lifecycle_manager:
            lifecycle_code = self._generate_lifecycle_manager(launch.lifecycle_manager)
            lines.append(f"    {lifecycle_code}")
            lines.append("    actions.append(lifecycle_manager)")
            lines.append("")

        # Build LaunchDescription
        lines.append("    return LaunchDescription(actions)")

        return "\n".join(lines)

    def _generate_config_variables(self, launch: nodes.LaunchDecl) -> List[str]:
        """Generate LaunchConfiguration variable declarations."""
        lines = []
        for arg in launch.arguments:
            lines.append(f"    {arg.name} = LaunchConfiguration('{arg.name}')")
        return lines

    def _generate_argument_declarations(self, launch: nodes.LaunchDecl) -> List[str]:
        """Generate DeclareLaunchArgument statements."""
        lines = ["    # Declare launch arguments"]
        for arg in launch.arguments:
            default = self._expression_to_python(arg.default_value) if arg.default_value else "None"
            lines.extend([
                f"    declare_{arg.name} = DeclareLaunchArgument(",
                f"        '{arg.name}',",
                f"        default_value={default},",
                f"        description=''",
                f"    )",
            ])
        return lines

    def _generate_group_action(self, group: nodes.GroupDecl) -> str:
        """Generate GroupAction for a node group."""
        lines = ["group_action = GroupAction(["]

        for node in group.nodes:
            node_code = self._generate_node_launch(node)
            lines.append(f"        {node_code},")

        namespace = self._expression_to_python(group.namespace)
        lines.append(f"    ], namespace={namespace})")

        return "\n".join(lines)

    def _generate_node_launch(self, node: nodes.NodeInstance) -> str:
        """Generate Node action for launch."""
        params = []

        # Build parameters dict
        if node.parameters:
            param_pairs = []
            for key, value in node.parameters.items():
                val_str = self._expression_to_python(value)
                param_pairs.append(f"'{key}': {val_str}")
            params.append(f"parameters=[{{{', '.join(param_pairs)}}}]")

        # Handle condition
        if node.condition:
            condition = self._expression_to_python(node.condition)
            params.append(f"condition=IfCondition(f'{{{condition}}}')")

        param_str = ",\n            ".join(params)

        return f'''Node(
            package='{self._camel_to_snake(node.node_type)}',
            executable='{self._camel_to_snake(node.node_type)}_node',
            name='{node.name}',
            {param_str}
        )'''

    def _generate_container_action(self, container: nodes.ContainerDecl) -> str:
        """Generate ComposableNodeContainer action."""
        container_name = self._expression_to_python(container.container_name)

        components = []
        for comp in container.components:
            comp_code = f'''ComposableNode(
                package='{self._camel_to_snake(comp.component_type)}',
                plugin='{comp.component_type}',
                name='{comp.name}'
            )'''
            components.append(comp_code)

        components_str = ",\n            ".join(components)

        return f'''container_action = ComposableNodeContainer(
        name={container_name},
        namespace='',
        package='rclcpp_components',
        executable='component_container',
        composable_node_descriptions=[
            {components_str}
        ]
    )'''

    def _generate_include_action(self, include: nodes.IncludeDecl) -> str:
        """Generate IncludeLaunchDescription action."""
        if isinstance(include.target, str):
            target_str = f'"{include.target}"'
        else:
            target_str = self._expression_to_python(include.target)

        if include.arguments:
            arg_pairs = []
            for key, value in include.arguments.items():
                val_str = self._expression_to_python(value)
                arg_pairs.append(f"'{key}': {val_str}")
            launch_args = f",\n        launch_arguments={{{', '.join(arg_pairs)}}}.items()"
        else:
            launch_args = ""

        return f'''include_action = IncludeLaunchDescription(
        PythonLaunchDescriptionSource([FindPackageShare(''), '/launch/', {target_str}]),
        {launch_args}
    )'''

    def _generate_lifecycle_manager(self, manager: nodes.LifecycleManagerDecl) -> str:
        """Generate lifecycle manager setup."""
        managed = ", ".join(f"'{n}'" for n in manager.managed_nodes)

        return f'''lifecycle_manager = LifecycleNode(
        package='lifecycle_manager',
        executable='lifecycle_manager',
        name='{manager.name}',
        parameters=[{{'managed_nodes': [{managed}]}}]
    )'''

    def _expression_to_python(self, expr: Optional[nodes.Expression]) -> str:
        """Convert expression to Python code."""
        if expr is None:
            return "None"

        if isinstance(expr, nodes.LiteralExpression):
            if expr.literal_type == "string":
                return f'"{expr.value}"'
            elif expr.literal_type == "bool":
                return str(expr.value)
            else:
                return str(expr.value)

        elif isinstance(expr, nodes.IdentifierExpression):
            return expr.name

        elif isinstance(expr, nodes.QualifiedIdentifierExpression):
            return "::".join(expr.parts)

        elif isinstance(expr, nodes.BinaryExpression):
            left = self._expression_to_python(expr.left)
            right = self._expression_to_python(expr.right)
            return f"({left} {expr.operator} {right})"

        return str(expr)

    def _camel_to_snake(self, name: str) -> str:
        """Convert CamelCase to snake_case."""
        import re
        s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
        return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
