"""Python code generator for NOS.

Generates ROS2 Python nodes from NOS AST.
"""

import logging
from typing import Dict, Any, List, Optional

from .generator import CodeGenerator, GenerationOutput
from ..ast import nodes
from ..semantic import SymbolTable, SymbolType
from ..security import validate_callback_code, SecurityError

# Configure audit logging
logger = logging.getLogger(__name__)


class PythonGenerator(CodeGenerator):
    """Generates Python ROS2 code from NOS AST."""

    def __init__(self, options: Dict[str, Any] = None):
        super().__init__(options)
        self.target = 'python'
        self.package_name: Optional[str] = None
        self.symbol_table: Optional[SymbolTable] = None

    def _reserved_keywords(self) -> set:
        """Python reserved keywords."""
        return {
            'False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await',
            'break', 'class', 'continue', 'def', 'del', 'elif', 'else',
            'except', 'finally', 'for', 'from', 'global', 'if', 'import',
            'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise',
            'return', 'try', 'while', 'with', 'yield'
        }

    def generate(self, ast: nodes.ASTNode, symbol_table: SymbolTable) -> GenerationOutput:
        """Generate Python code from AST."""
        self.output = GenerationOutput()
        self.symbol_table = symbol_table

        if isinstance(ast, nodes.File):
            if ast.package:
                self.package_name = ast.package.name

            for decl in ast.declarations:
                if isinstance(decl, nodes.NodeDecl):
                    self._generate_node(decl)
                elif isinstance(decl, nodes.LaunchDecl):
                    self._generate_launch(decl)
        elif isinstance(ast, nodes.NodeDecl):
            self._generate_node(ast)
        elif isinstance(ast, nodes.LaunchDecl):
            self._generate_launch(ast)

        return self.output

    def _generate_node(self, node: nodes.NodeDecl) -> None:
        """Generate Python code for a node."""
        class_name = node.name
        base_class = "NOSLifecycleNode" if node.lifecycle else "NOSNode"

        # Generate imports
        imports = self._generate_node_imports(node)

        # Generate class definition
        class_def = self._generate_node_class(node, class_name, base_class)

        # Generate main entry point
        main = self._generate_main_function(class_name)

        # Combine all parts
        content = f'''# AUTO-GENERATED by NOS - Do not edit manually
# Source: {node.location}

{imports}

{class_def}

{main}
'''

        file_name = f"{self._camel_to_snake(class_name)}_node.py"
        self.output.add_file(file_name, content)

    def _generate_node_imports(self, node: nodes.NodeDecl) -> str:
        """Generate import statements for a node."""
        imports = [
            "import rclpy",
            "from rclpy.node import Node",
            "from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy",
            "from rcl_interfaces.msg import ParameterDescriptor, FloatingPointRange, IntegerRange",
            "from nos.runtime import NOSNode, NOSLifecycleNode",
        ]

        # Add message type imports
        message_packages = set()
        for sub in node.subscriptions:
            if sub.message_type.package:
                message_packages.add(sub.message_type.package)
        for pub in node.publications:
            if pub.message_type.package:
                message_packages.add(pub.message_type.package)

        for pkg in sorted(message_packages):
            imports.append(f"from {pkg}.msg import *")

        return "\n".join(imports)

    def _generate_node_class(self, node: nodes.NodeDecl, class_name: str,
                             base_class: str) -> str:
        """Generate node class definition."""
        node_name = self._camel_to_snake(class_name)

        # Generate docstring
        docstring = f'    """Auto-generated base class for {class_name} node."""'

        # Generate __init__ method
        init_method = self._generate_init_method(node, node_name)

        # Generate parameter properties
        param_properties = self._generate_parameter_properties(node)

        # Generate parameter declaration method
        param_method = self._generate_declare_parameters_method(node)

        # Generate communication setup method
        comm_method = self._generate_setup_communications_method(node)

        # Generate callback wrappers
        callbacks = self._generate_callbacks(node)

        # Generate lifecycle methods if managed
        lifecycle_methods = self._generate_lifecycle_methods(node) if node.lifecycle else ""

        return f'''class {class_name}Base({base_class}):
{docstring}

{init_method}

{param_properties}

{param_method}

{comm_method}

{callbacks}

{lifecycle_methods}
'''

    def _generate_parameter_properties(self, node: nodes.NodeDecl) -> str:
        """Generate property accessors for parameters."""
        lines = []
        for param in node.parameters:
            if isinstance(param.type, nodes.StructType):
                # Generate flattened properties for struct fields
                for field in param.type.fields:
                    full_name = f"{param.name}.{field.name}"
                    prop_name = f"{param.name}_{field.name}"
                    lines.append(f"    @property")
                    lines.append(f"    def {prop_name}(self):")
                    lines.append(f"        return self.get_parameter('{full_name}').value")
                    lines.append("")
                
                # Also a top-level property for the whole struct
                lines.append(f"    @property")
                lines.append(f"    def {param.name}(self):")
                lines.append(f"        return self.get_parameter('{param.name}').value")
                lines.append("")
            else:
                lines.append(f"    @property")
                lines.append(f"    def {param.name}(self):")
                lines.append(f"        return self.get_parameter('{param.name}').value")
                lines.append("")
        
        return "\n".join(lines)

    def _generate_init_method(self, node: nodes.NodeDecl, node_name: str) -> str:
        """Generate __init__ method."""
        lines = [
            f"    def __init__(self, node_name: str = '{node_name}'):",
            f"        super().__init__(node_name)",
            "",
            "        # Parameter declarations",
            "        self._declare_nos_parameters()",
            "",
            "        # Setup communications",
            "        self._setup_communications()",
            "",
            "        # Call user initialization",
            "        self.on_init()",
        ]

        return "\n".join(lines)

    def _generate_declare_parameters_method(self, node: nodes.NodeDecl) -> str:
        """Generate parameter declaration method."""
        lines = ["    def _declare_nos_parameters(self):"]

        if not node.parameters:
            lines.append("        pass")
            return "\n".join(lines)

        for param in node.parameters:
            if isinstance(param.type, nodes.StructType):
                # Flatten struct parameters for ROS2
                for field in param.type.fields:
                    param_name = f"{param.name}.{field.name}"
                    default_value = "None"
                    
                    if param.default_value and isinstance(param.default_value, nodes.StructInitializerExpression):
                        if field.name in param.default_value.fields:
                            default_value = self._expression_to_python(param.default_value.fields[field.name])
                    
                    lines.append(f"        self.declare_parameter('{param_name}', {default_value})")
            else:
                param_name = param.name
                default_value = self._expression_to_python(param.default_value) if param.default_value else "None"

                descriptor = ""
                if param.constraints:
                    constraint_code = self._generate_parameter_constraints(param)
                    if constraint_code:
                        descriptor = f", descriptor={constraint_code}"

                lines.append(f"        self.declare_parameter('{param_name}', {default_value}{descriptor})")

        return "\n".join(lines)

    def _generate_parameter_constraints(self, param: nodes.ParameterDecl) -> str:
        """Generate parameter constraint descriptor."""
        descriptor_parts = []

        for constraint in param.constraints:
            if constraint.name == "range":
                if len(constraint.arguments) >= 2:
                    min_val = self._expression_to_python(constraint.arguments[0])
                    max_val = self._expression_to_python(constraint.arguments[1])
                    param_type = self._get_python_type(param.type)
                    if "float" in param_type:
                        descriptor_parts.append(
                            f"floating_point_range=[FloatingPointRange(from_value={min_val}, to_value={max_val})]"
                        )
                    else:
                        descriptor_parts.append(
                            f"integer_range=[IntegerRange(from_value={int(min_val)}, to_value={int(max_val)})]"
                        )

        if descriptor_parts:
            return f"ParameterDescriptor({', '.join(descriptor_parts)})"
        return ""

    def _generate_setup_communications_method(self, node: nodes.NodeDecl) -> str:
        """Generate communication setup method."""
        lines = ["    def _setup_communications(self):"]

        if not (node.subscriptions or node.publications or node.services):
            lines.append("        pass")
            return "\n".join(lines)

        # Generate subscriptions
        for sub in node.subscriptions:
            msg_type = sub.message_type.name
            topic_expr = self._expression_to_python(sub.topic)
            callback_name = f"_on_{sub.name}_received"
            qos = self._generate_qos_config(sub.qos)

            lines.extend([
                f"        self._{sub.name}_sub = self.create_subscription(",
                f"            {msg_type}, {topic_expr}, self.{callback_name}, {qos}",
                f"        )"
            ])

        lines.append("")

        # Generate publishers
        for pub in node.publications:
            msg_type = pub.message_type.name
            topic_expr = self._expression_to_python(pub.topic)
            qos = self._generate_qos_config(pub.qos)

            lines.extend([
                f"        self.{pub.name} = self.create_publisher(",
                f"            {msg_type}, {topic_expr}, {qos}",
                f"        )"
            ])

        lines.append("")

        # Generate services
        for svc in node.services:
            svc_type = svc.service_type.name
            svc_name = self._expression_to_python(svc.service_name)
            callback_name = f"_{svc.name}_callback"

            lines.extend([
                f"        self._{svc.name}_srv = self.create_service(",
                f"            {svc_type}, {svc_name}, self.{callback_name}",
                f"        )"
            ])

        return "\n".join(lines)

    def _generate_qos_config(self, qos: Optional[nodes.QoSConfig]) -> str:
        """Generate QoS configuration code."""
        if qos is None:
            return "10"

        reliability = qos.reliability if qos.reliability else "reliable"
        depth = qos.depth if qos.depth else 10

        if reliability == "reliable":
            return f"QoSProfile(reliability=ReliabilityPolicy.RELIABLE, depth={depth})"
        else:
            return f"QoSProfile(reliability=ReliabilityPolicy.BEST_EFFORT, depth={depth})"

    def _generate_callbacks(self, node: nodes.NodeDecl) -> str:
        """Generate callback method wrappers with security validation."""
        callbacks = []
        security_errors = []

        # Get list of events that have user implementations
        user_implemented_events = {cb.event for cb in node.callbacks}

        # Generate subscription callbacks
        for sub in node.subscriptions:
            msg_type = sub.message_type.name
            callback_name = f"{sub.name}_received"
            
            # Wrapper
            wrapper = f'''    def _on_{sub.name}_received(self, msg: {msg_type}):
        """Wrapper for {sub.name} subscription callback."""
        try:
            self.{callback_name}(msg)
        except Exception as e:
            self.get_logger().error(f"Error in {sub.name} callback: {{e}}")
'''
            callbacks.append(wrapper)
            
            # Default implementation if not provided by user
            if callback_name not in user_implemented_events:
                default_impl = f'''
    def {callback_name}(self, msg: {msg_type}):
        """Default implementation for {sub.name} messages."""
        pass
'''
                callbacks.append(default_impl)

        # Generate service callbacks
        for svc in node.services:
            svc_type = svc.service_type.name
            callback_name = f"{svc.name}_callback"
            user_callback_name = f"{svc.name}_request"
            
            # Wrapper
            wrapper = f'''    def _{callback_name}(self, request, response):
        """Wrapper for {svc.name} service callback."""
        try:
            return self.{user_callback_name}(request, response)
        except Exception as e:
            self.get_logger().error(f"Error in {svc.name} service: {{e}}")
            response.success = False
            return response
'''
            callbacks.append(wrapper)
            
            # Default implementation if not provided by user
            if user_callback_name not in user_implemented_events:
                default_impl = f'''
    def {user_callback_name}(self, request, response):
        """Default implementation for {svc.name} requests."""
        response.success = True
        return response
'''
                callbacks.append(default_impl)

        # Generate lifecycle callbacks with security validation
        import textwrap
        for cb in node.callbacks:
            # Validate embedded Python code for security
            body = cb.body
            wrapped_body = None
            if body:
                # Clean up body for validation and generation
                # We strip leading/trailing newlines but KEEP leading spaces on the first line
                # so that textwrap.dedent can work correctly.
                cleaned_body = body.strip('\r\n')
                cleaned_body = textwrap.dedent(cleaned_body)
                
                # Interpolate NOS parameters BEFORE validation
                # so that the code is valid Python syntax.
                cleaned_body = self._interpolate_nos_parameters(cleaned_body)
                
                validation_result = validate_callback_code(cleaned_body, strict=True)
                if not validation_result.is_safe:
                    security_errors.extend(validation_result.errors)
                    logger.warning(
                        f"Security validation failed for callback '{cb.event}': "
                        f"{validation_result.errors}"
                    )
                    # Replace dangerous code with a safe error message
                    body = f"        # SECURITY ERROR: Callback code blocked due to security violations:\n"
                    body += "        # " + "\n        # ".join(validation_result.errors)
                    body += "\n        self.get_logger().error('Security validation failed for callback')"
                    body += "\n        pass"
                else:
                    # Use cleaned and interpolated body
                    body = cleaned_body
                    
                    if validation_result.warnings:
                        # Prepend warnings as comments
                        body = f"# SECURITY WARNINGS:\n"
                        body += "# " + "\n# ".join(validation_result.warnings) + "\n" + body
                        # Log audit event
                        logger.info(
                            f"Callback '{cb.event}' passed security validation with warnings: "
                            f"{validation_result.warnings}"
                        )
                    else:
                        # Log successful validation
                        logger.info(f"Callback '{cb.event}' passed security validation")

                # Wrap validated code in try/except for runtime safety
                # Note: body already has interpolation applied here
                wrapped_body = self._wrap_code_in_try_except(body, cb.event)

            if cb.event == "on_init":
                if wrapped_body:
                    callback_body = wrapped_body
                else:
                    callback_body = "        pass"
                callback = f'''    def on_init(self):
        """User initialization callback."""
{callback_body}
'''
            elif cb.event == "on_shutdown":
                if wrapped_body:
                    callback_body = wrapped_body
                else:
                    callback_body = "        pass"
                callback = f'''    def on_shutdown(self):
        """User shutdown callback."""
{callback_body}
'''
            else:
                method_params = ["self"]
                for p in cb.parameters:
                    method_params.append(f"{p.name}: {self._get_python_type(p.type)}")
                
                params_str = ", ".join(method_params)
                
                if wrapped_body:
                    callback_body = wrapped_body
                else:
                    callback_body = "        pass"
                callback = f'''    def {cb.event}({params_str}):
        """User callback: {cb.event}."""
{callback_body}
'''
            callbacks.append(callback)

        # Store security errors for later reporting
        if security_errors:
            self.output.security_errors = security_errors
            logger.error(f"Security errors found in callbacks: {security_errors}")

        # Log audit event for generated code
        logger.info(f"Generated {len(callbacks)} callbacks for node")

        return "\n".join(callbacks)

    def _wrap_code_in_try_except(self, body: str, callback_name: str) -> str:
        """Wrap callback body in try/except for runtime safety.

        Args:
            body: The callback body code (should be pre-interpolated)
            callback_name: Name of the callback for error messages

        Returns:
            Wrapped code string
        """
        if not body or not body.strip():
            return "        pass"

        # Indent the body content
        # Level 3 (12 spaces) to be nested inside 'try:' which is at level 2 (8 spaces)
        indented_body = self._indent(body.strip(), 3)

        # Generate the wrapped code
        wrapped = f'''        try:
{indented_body}
        except Exception as e:
            self.get_logger().error(f"Error in {callback_name} callback: {{e}}")
            raise  # Re-raise to allow upstream handling'''

        return wrapped

    def _interpolate_nos_parameters(self, body: str) -> str:
        """Replace NOS parameter interpolation ${...} with self.property_name."""
        import re
        # Match ${param.field} or ${param}
        pattern = r'\$\{([a-zA-Z0-9_\.]+)\}'
        
        def replace_param(match):
            param_path = match.group(1)
            # Convert param.field to param_field for property access
            return f"self.{param_path.replace('.', '_')}"
            
        return re.sub(pattern, replace_param, body)

    def _generate_lifecycle_methods(self, node: nodes.NodeDecl) -> str:
        """Generate lifecycle management methods."""
        return '''    def on_configure(self, state):
        """Configure the node."""
        self._setup_communications()
        return TransitionCallbackReturn.SUCCESS

    def on_activate(self, state):
        """Activate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_deactivate(self, state):
        """Deactivate the node."""
        return TransitionCallbackReturn.SUCCESS

    def on_cleanup(self, state):
        """Cleanup the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS

    def on_shutdown(self, state):
        """Shutdown the node."""
        self.on_shutdown()
        return TransitionCallbackReturn.SUCCESS
'''

    def _generate_main_function(self, class_name: str) -> str:
        """Generate main entry point."""
        return f'''def main(args=None):
    rclpy.init(args=args)
    node = {class_name}Base()
    executor = rclpy.executors.SingleThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
'''

    def _generate_launch(self, launch: nodes.LaunchDecl) -> None:
        """Generate Python launch file."""
        content = self._generate_launch_content(launch)
        file_name = f"{self._camel_to_snake(launch.name)}_launch.py"
        self.output.add_file(file_name, content)

    def _generate_launch_content(self, launch: nodes.LaunchDecl) -> str:
        """Generate launch file content."""
        lines = [
            "# AUTO-GENERATED by NOS - Do not edit manually",
            f"# Source: {launch.location}",
            "",
            "from launch import LaunchDescription",
            "from launch.actions import DeclareLaunchArgument, GroupAction",
            "from launch.substitutions import LaunchConfiguration",
            "from launch_ros.actions import Node, ComposableNodeContainer",
            "from launch_ros.descriptions import ComposableNode",
            "",
            "",
            "def generate_launch_description():",
        ]

        # Generate argument declarations
        if launch.arguments:
            for arg in launch.arguments:
                arg_name = arg.name
                default = self._expression_to_python(arg.default_value) if arg.default_value else "None"
                lines.append(f"    {arg_name} = LaunchConfiguration('{arg_name}')")
            lines.append("")

            for arg in launch.arguments:
                arg_name = arg.name
                default = self._expression_to_python(arg.default_value) if arg.default_value else "None"
                lines.append(f"    declare_{arg_name} = DeclareLaunchArgument(")
                lines.append(f"        '{arg_name}', default_value={default}")
                lines.append(f"    )")
            lines.append("")

        # Generate launch actions
        actions = []

        for group in launch.groups:
            group_code = self._generate_group(group)
            actions.append(group_code)

        for container in launch.containers:
            container_code = self._generate_container(container)
            actions.append(container_code)

        # Build launch description
        lines.append("    return LaunchDescription([")

        # Add argument declarations first
        if launch.arguments:
            for arg in launch.arguments:
                lines.append(f"        declare_{arg.name},")

        # Add other actions
        for action in actions:
            lines.append(f"        {action},")

        lines.append("    ])")

        return "\n".join(lines)

    def _generate_group(self, group: nodes.GroupDecl) -> str:
        """Generate group action."""
        namespace = self._expression_to_python(group.namespace)

        nodes_code = []
        for node in group.nodes:
            node_code = self._generate_node_instance(node)
            nodes_code.append(node_code)

        nodes_str = "\n        ".join(nodes_code)

        return f'''GroupAction([
        {nodes_str}
    ], namespace={namespace})'''

    def _generate_node_instance(self, node: nodes.NodeInstance) -> str:
        """Generate node instance code."""
        params = []
        if node.parameters:
            param_dict = "{"
            for key, value in node.parameters.items():
                val_str = self._expression_to_python(value)
                param_dict += f"'{key}': {val_str}, "
            param_dict += "}"
            params.append(f"parameters=[{param_dict}]")

        param_str = ", ".join(params)

        return f'''Node(
            package='{self._camel_to_snake(node.node_type)}',
            executable='{self._camel_to_snake(node.node_type)}_node',
            name='{node.name}',
            {param_str}
        )'''

    def _generate_container(self, container: nodes.ContainerDecl) -> str:
        """Generate composable node container."""
        components = []
        for comp in container.components:
            comp_code = f'''ComposableNode(
                package='{self._camel_to_snake(comp.component_type)}',
                plugin='{comp.component_type}',
                name='{comp.name}'
            )'''
            components.append(comp_code)

        components_str = ",\n            ".join(components)

        return f'''ComposableNodeContainer(
            name='{container.name}',
            namespace='',
            package='rclcpp_components',
            executable='component_container',
            composable_node_descriptions=[
                {components_str}
            ]
        )'''

    def _expression_to_python(self, expr: Optional[nodes.Expression]) -> str:
        """Convert expression to Python code."""
        if expr is None:
            return "None"

        if isinstance(expr, nodes.LiteralExpression):
            if expr.literal_type == "string":
                return f'"{expr.value}"'
            elif expr.literal_type == "bool":
                return str(expr.value)
            else:
                return str(expr.value)

        elif isinstance(expr, nodes.IdentifierExpression):
            return expr.name

        elif isinstance(expr, nodes.QualifiedIdentifierExpression):
            return "::".join(expr.parts)

        elif isinstance(expr, nodes.BinaryExpression):
            left = self._expression_to_python(expr.left)
            right = self._expression_to_python(expr.right)
            op_map = {"&&": "and", "||": "or", "==": "==", "!=": "!=",
                     "<": "<", ">": ">", "<=": "<=", ">=": ">=",
                     "+": "+", "-": "-", "*": "*", "/": "/", "%": "%"}
            op = op_map.get(expr.operator, expr.operator)
            return f"({left} {op} {right})"

        elif isinstance(expr, nodes.UnaryExpression):
            operand = self._expression_to_python(expr.operand)
            if expr.operator == "!":
                return f"(not {operand})"
            return f"({expr.operator}{operand})"

        elif isinstance(expr, nodes.MemberAccessExpression):
            obj = self._expression_to_python(expr.object)
            return f"{obj}.{expr.member}"

        return str(expr)

    def _get_python_type(self, type_node: Optional[nodes.Type]) -> str:
        """Convert NOS type to Python type annotation."""
        if type_node is None:
            return "Any"

        if isinstance(type_node, nodes.PrimitiveType):
            type_map = {
                "bool": "bool",
                "int": "int",
                "float": "float",
                "double": "float",
                "string": "str",
                "duration": "Duration",
                "time": "Time"
            }
            return type_map.get(type_node.kind.value, "Any")

        elif isinstance(type_node, nodes.QualifiedType):
            return type_node.name

        elif isinstance(type_node, nodes.ListType):
            element = self._get_python_type(type_node.element_type)
            return f"List[{element}]"

        return "Any"
